[setup]
# Especifica a linguagem e versão
language = "python"
version = "3.10"

[dependencies]
# Lista de pacotes do sistema a serem instalados
apt = ["build-essential", "libmariadb-dev-compat", "libmariadb-dev", "pkg-config"]

[commands.build]
# Comando para criar o ambiente virtual e instalar dependências
run = """
python -m venv /opt/venv
. /opt/venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
"""

[commands.start]
# Comando para iniciar o servidor
run = """
. /opt/venv/bin/activate
gunicorn core.wsgi --log-file -
"""
